modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Brass-Goggled-Coders/T-Shirt Cannon/issues"

[[mods]]
    modId="tshirtcannon"
    version="${file.jarVersion}"
    displayName="T-Shirt Cannon"
    authors="SkySom"
    description='''
    '''